/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Participant = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'medicalConditions' : IDL.Text,
  'emergencyContact' : IDL.Text,
  'govtId' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
  'mobile' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'participants' : IDL.Vec(Participant),
  'userId' : IDL.Text,
  'trekId' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'addOns' : IDL.Vec(IDL.Text),
  'batchId' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'userId' : IDL.Text,
  'trekId' : IDL.Text,
  'reviewerCity' : IDL.Text,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'trekDate' : IDL.Text,
  'rating' : IDL.Nat,
  'helpful' : IDL.Nat,
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Trek = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'duration' : IDL.Text,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'bestTime' : IDL.Text,
  'description' : IDL.Text,
  'imageQuery' : IDL.Text,
  'distance' : IDL.Text,
  'nearestAirport' : IDL.Text,
  'price' : IDL.Text,
  'maxAltitude' : IDL.Text,
  'nearestRailhead' : IDL.Text,
  'groupSize' : IDL.Text,
  'startPoint' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const Yatra = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'duration' : IDL.Text,
  'startEnd' : IDL.Text,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'bestTime' : IDL.Text,
  'description' : IDL.Text,
  'imageQuery' : IDL.Text,
  'price' : IDL.Text,
});
export const Batch = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Text,
  'maxCapacity' : IDL.Nat,
  'trekId' : IDL.Text,
  'bookedCount' : IDL.Nat,
  'basePrice' : IDL.Nat,
  'batchType' : IDL.Text,
  'startDate' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'imageQuery' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const GearItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'spec' : IDL.Text,
  'deposit' : IDL.Nat,
  'pricePerDay' : IDL.Nat,
  'category' : IDL.Text,
  'brand' : IDL.Text,
});
export const BookingInquiry = IDL.Record({
  'trekInterest' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'hearAboutUs' : IDL.Text,
  'preferredDates' : IDL.Text,
  'phone' : IDL.Text,
  'groupSize' : IDL.Text,
  'specialRequirements' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([Booking], [IDL.Text], []),
  'createReview' : IDL.Func([Review], [IDL.Text], []),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getPackageById' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
  'getTrek' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
  'getYatra' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
  'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listBatches' : IDL.Func([IDL.Text], [IDL.Vec(Batch)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listGearItems' : IDL.Func([], [IDL.Vec(GearItem)], ['query']),
  'listPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'listReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'listTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'listUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'listYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
  'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'submitBookingInquiry' : IDL.Func([BookingInquiry], [IDL.Text], []),
  'updateBatchAvailability' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Participant = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'medicalConditions' : IDL.Text,
    'emergencyContact' : IDL.Text,
    'govtId' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
    'mobile' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'participants' : IDL.Vec(Participant),
    'userId' : IDL.Text,
    'trekId' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'addOns' : IDL.Vec(IDL.Text),
    'batchId' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'userId' : IDL.Text,
    'trekId' : IDL.Text,
    'reviewerCity' : IDL.Text,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'trekDate' : IDL.Text,
    'rating' : IDL.Nat,
    'helpful' : IDL.Nat,
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Trek = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'duration' : IDL.Text,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'bestTime' : IDL.Text,
    'description' : IDL.Text,
    'imageQuery' : IDL.Text,
    'distance' : IDL.Text,
    'nearestAirport' : IDL.Text,
    'price' : IDL.Text,
    'maxAltitude' : IDL.Text,
    'nearestRailhead' : IDL.Text,
    'groupSize' : IDL.Text,
    'startPoint' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const Yatra = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'duration' : IDL.Text,
    'startEnd' : IDL.Text,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'bestTime' : IDL.Text,
    'description' : IDL.Text,
    'imageQuery' : IDL.Text,
    'price' : IDL.Text,
  });
  const Batch = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Text,
    'maxCapacity' : IDL.Nat,
    'trekId' : IDL.Text,
    'bookedCount' : IDL.Nat,
    'basePrice' : IDL.Nat,
    'batchType' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'imageQuery' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const GearItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'spec' : IDL.Text,
    'deposit' : IDL.Nat,
    'pricePerDay' : IDL.Nat,
    'category' : IDL.Text,
    'brand' : IDL.Text,
  });
  const BookingInquiry = IDL.Record({
    'trekInterest' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'hearAboutUs' : IDL.Text,
    'preferredDates' : IDL.Text,
    'phone' : IDL.Text,
    'groupSize' : IDL.Text,
    'specialRequirements' : IDL.Text,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func([Booking], [IDL.Text], []),
    'createReview' : IDL.Func([Review], [IDL.Text], []),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getPackageById' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
    'getTrek' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
    'getYatra' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
    'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listBatches' : IDL.Func([IDL.Text], [IDL.Vec(Batch)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listGearItems' : IDL.Func([], [IDL.Vec(GearItem)], ['query']),
    'listPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'listReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'listTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'listUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'listYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
    'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'submitBookingInquiry' : IDL.Func([BookingInquiry], [IDL.Text], []),
    'updateBatchAvailability' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };