/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ParticipantInput = IDL.Record({
  'age' : IDL.Nat,
  'govtIdType' : IDL.Text,
  'medicalConditions' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
  'emergencyContactPhone' : IDL.Text,
  'emergencyContactName' : IDL.Text,
  'mobile' : IDL.Text,
  'lastName' : IDL.Text,
  'govtIdNumber' : IDL.Text,
  'firstName' : IDL.Text,
});
export const AddOns = IDL.Record({
  'gearTent' : IDL.Bool,
  'gearBoots' : IDL.Bool,
  'porterDays' : IDL.Nat,
  'mule' : IDL.Bool,
  'muleDays' : IDL.Nat,
  'gearSleepingBag' : IDL.Bool,
  'travelInsurance' : IDL.Bool,
  'porter' : IDL.Bool,
});
export const BookingInput = IDL.Record({
  'participants' : IDL.Vec(ParticipantInput),
  'promoCode' : IDL.Text,
  'advanceAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'addOns' : AddOns,
  'trekSlug' : IDL.Text,
  'paymentType' : IDL.Text,
  'batchDate' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'userId' : IDL.Text,
  'trekId' : IDL.Text,
  'reviewerCity' : IDL.Text,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'trekDate' : IDL.Text,
  'rating' : IDL.Nat,
  'helpful' : IDL.Nat,
});
export const BatchAvailability = IDL.Record({
  'totalSeats' : IDL.Nat,
  'bookedSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'trekSlug' : IDL.Text,
  'price' : IDL.Nat,
  'batchDate' : IDL.Text,
  'batchType' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'participants' : IDL.Vec(ParticipantInput),
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'promoCode' : IDL.Text,
  'advanceAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'addOns' : AddOns,
  'trekSlug' : IDL.Text,
  'contactEmail' : IDL.Text,
  'paymentType' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'batchDate' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Trek = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'duration' : IDL.Text,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'bestTime' : IDL.Text,
  'description' : IDL.Text,
  'imageQuery' : IDL.Text,
  'distance' : IDL.Text,
  'nearestAirport' : IDL.Text,
  'price' : IDL.Text,
  'maxAltitude' : IDL.Text,
  'nearestRailhead' : IDL.Text,
  'groupSize' : IDL.Text,
  'startPoint' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const Yatra = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'duration' : IDL.Text,
  'startEnd' : IDL.Text,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'bestTime' : IDL.Text,
  'description' : IDL.Text,
  'imageQuery' : IDL.Text,
  'price' : IDL.Text,
});
export const Batch = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Text,
  'maxCapacity' : IDL.Nat,
  'trekId' : IDL.Text,
  'bookedCount' : IDL.Nat,
  'basePrice' : IDL.Nat,
  'batchType' : IDL.Text,
  'startDate' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'imageQuery' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const GearItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'spec' : IDL.Text,
  'deposit' : IDL.Nat,
  'pricePerDay' : IDL.Nat,
  'category' : IDL.Text,
  'brand' : IDL.Text,
});
export const BookingInquiry = IDL.Record({
  'trekInterest' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'hearAboutUs' : IDL.Text,
  'preferredDates' : IDL.Text,
  'phone' : IDL.Text,
  'groupSize' : IDL.Text,
  'specialRequirements' : IDL.Text,
});

export const idlService = IDL.Service({
  'cancelBooking' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'createBooking' : IDL.Func([BookingInput], [IDL.Text], []),
  'createReview' : IDL.Func([Review], [IDL.Text], []),
  'getAvailableSeats' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getBatchAvailability' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BatchAvailability)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getPackageById' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
  'getTrek' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
  'getUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getYatra' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
  'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listBatches' : IDL.Func([IDL.Text], [IDL.Vec(Batch)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listGearItems' : IDL.Func([], [IDL.Vec(GearItem)], ['query']),
  'listPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'listReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'listTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'listUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'listYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
  'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'submitBookingInquiry' : IDL.Func([BookingInquiry], [IDL.Text], []),
  'updateBatchAvailability' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ParticipantInput = IDL.Record({
    'age' : IDL.Nat,
    'govtIdType' : IDL.Text,
    'medicalConditions' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
    'emergencyContactPhone' : IDL.Text,
    'emergencyContactName' : IDL.Text,
    'mobile' : IDL.Text,
    'lastName' : IDL.Text,
    'govtIdNumber' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const AddOns = IDL.Record({
    'gearTent' : IDL.Bool,
    'gearBoots' : IDL.Bool,
    'porterDays' : IDL.Nat,
    'mule' : IDL.Bool,
    'muleDays' : IDL.Nat,
    'gearSleepingBag' : IDL.Bool,
    'travelInsurance' : IDL.Bool,
    'porter' : IDL.Bool,
  });
  const BookingInput = IDL.Record({
    'participants' : IDL.Vec(ParticipantInput),
    'promoCode' : IDL.Text,
    'advanceAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'addOns' : AddOns,
    'trekSlug' : IDL.Text,
    'paymentType' : IDL.Text,
    'batchDate' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'userId' : IDL.Text,
    'trekId' : IDL.Text,
    'reviewerCity' : IDL.Text,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'trekDate' : IDL.Text,
    'rating' : IDL.Nat,
    'helpful' : IDL.Nat,
  });
  const BatchAvailability = IDL.Record({
    'totalSeats' : IDL.Nat,
    'bookedSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'trekSlug' : IDL.Text,
    'price' : IDL.Nat,
    'batchDate' : IDL.Text,
    'batchType' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'participants' : IDL.Vec(ParticipantInput),
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'promoCode' : IDL.Text,
    'advanceAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'addOns' : AddOns,
    'trekSlug' : IDL.Text,
    'contactEmail' : IDL.Text,
    'paymentType' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'batchDate' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Trek = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'duration' : IDL.Text,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'bestTime' : IDL.Text,
    'description' : IDL.Text,
    'imageQuery' : IDL.Text,
    'distance' : IDL.Text,
    'nearestAirport' : IDL.Text,
    'price' : IDL.Text,
    'maxAltitude' : IDL.Text,
    'nearestRailhead' : IDL.Text,
    'groupSize' : IDL.Text,
    'startPoint' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const Yatra = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'duration' : IDL.Text,
    'startEnd' : IDL.Text,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'bestTime' : IDL.Text,
    'description' : IDL.Text,
    'imageQuery' : IDL.Text,
    'price' : IDL.Text,
  });
  const Batch = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Text,
    'maxCapacity' : IDL.Nat,
    'trekId' : IDL.Text,
    'bookedCount' : IDL.Nat,
    'basePrice' : IDL.Nat,
    'batchType' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'imageQuery' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const GearItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'spec' : IDL.Text,
    'deposit' : IDL.Nat,
    'pricePerDay' : IDL.Nat,
    'category' : IDL.Text,
    'brand' : IDL.Text,
  });
  const BookingInquiry = IDL.Record({
    'trekInterest' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'hearAboutUs' : IDL.Text,
    'preferredDates' : IDL.Text,
    'phone' : IDL.Text,
    'groupSize' : IDL.Text,
    'specialRequirements' : IDL.Text,
  });
  
  return IDL.Service({
    'cancelBooking' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createBooking' : IDL.Func([BookingInput], [IDL.Text], []),
    'createReview' : IDL.Func([Review], [IDL.Text], []),
    'getAvailableSeats' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getBatchAvailability' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BatchAvailability)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getPackageById' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
    'getTrek' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
    'getUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getYatra' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
    'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listBatches' : IDL.Func([IDL.Text], [IDL.Vec(Batch)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listGearItems' : IDL.Func([], [IDL.Vec(GearItem)], ['query']),
    'listPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'listReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'listTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'listUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'listYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
    'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'submitBookingInquiry' : IDL.Func([BookingInquiry], [IDL.Text], []),
    'updateBatchAvailability' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };