/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOns {
  'gearTent' : boolean,
  'gearBoots' : boolean,
  'porterDays' : bigint,
  'mule' : boolean,
  'muleDays' : bigint,
  'gearSleepingBag' : boolean,
  'travelInsurance' : boolean,
  'porter' : boolean,
}
export interface Batch {
  'id' : string,
  'endDate' : string,
  'maxCapacity' : bigint,
  'trekId' : string,
  'bookedCount' : bigint,
  'basePrice' : bigint,
  'batchType' : string,
  'startDate' : string,
}
export interface BatchAvailability {
  'totalSeats' : bigint,
  'bookedSeats' : bigint,
  'availableSeats' : bigint,
  'trekSlug' : string,
  'price' : bigint,
  'batchDate' : string,
  'batchType' : string,
}
export interface BlogPost {
  'id' : string,
  'title' : string,
  'date' : string,
  'imageQuery' : string,
  'excerpt' : string,
  'category' : string,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'participants' : Array<ParticipantInput>,
  'userId' : string,
  'createdAt' : bigint,
  'promoCode' : string,
  'advanceAmount' : bigint,
  'totalAmount' : bigint,
  'addOns' : AddOns,
  'trekSlug' : string,
  'contactEmail' : string,
  'paymentType' : string,
  'paidAmount' : bigint,
  'batchDate' : string,
  'contactPhone' : string,
}
export interface BookingInput {
  'participants' : Array<ParticipantInput>,
  'promoCode' : string,
  'advanceAmount' : bigint,
  'totalAmount' : bigint,
  'addOns' : AddOns,
  'trekSlug' : string,
  'paymentType' : string,
  'batchDate' : string,
}
export interface BookingInquiry {
  'trekInterest' : string,
  'name' : string,
  'email' : string,
  'hearAboutUs' : string,
  'preferredDates' : string,
  'phone' : string,
  'groupSize' : string,
  'specialRequirements' : string,
}
export type BookingStatus = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface GearItem {
  'id' : string,
  'name' : string,
  'spec' : string,
  'deposit' : bigint,
  'pricePerDay' : bigint,
  'category' : string,
  'brand' : string,
}
export interface Package {
  'id' : string,
  'duration' : string,
  'name' : string,
  'description' : string,
  'inclusions' : Array<string>,
  'highlights' : Array<string>,
  'category' : string,
  'price' : bigint,
  'images' : Array<string>,
}
export interface ParticipantInput {
  'age' : bigint,
  'govtIdType' : string,
  'medicalConditions' : string,
  'email' : string,
  'gender' : string,
  'emergencyContactPhone' : string,
  'emergencyContactName' : string,
  'mobile' : string,
  'lastName' : string,
  'govtIdNumber' : string,
  'firstName' : string,
}
export interface Review {
  'id' : string,
  'verified' : boolean,
  'userId' : string,
  'trekId' : string,
  'reviewerCity' : string,
  'reviewText' : string,
  'reviewerName' : string,
  'trekDate' : string,
  'rating' : bigint,
  'helpful' : bigint,
}
export interface Trek {
  'id' : string,
  'region' : string,
  'duration' : string,
  'difficulty' : string,
  'name' : string,
  'bestTime' : string,
  'description' : string,
  'imageQuery' : string,
  'distance' : string,
  'nearestAirport' : string,
  'price' : string,
  'maxAltitude' : string,
  'nearestRailhead' : string,
  'groupSize' : string,
  'startPoint' : string,
  'ageGroup' : string,
}
export interface Yatra {
  'id' : string,
  'region' : string,
  'duration' : string,
  'startEnd' : string,
  'difficulty' : string,
  'name' : string,
  'bestTime' : string,
  'description' : string,
  'imageQuery' : string,
  'price' : string,
}
export interface _SERVICE {
  'cancelBooking' : ActorMethod<[string, string], boolean>,
  'createBooking' : ActorMethod<[BookingInput], string>,
  'createReview' : ActorMethod<[Review], string>,
  'getAvailableSeats' : ActorMethod<[string, string], bigint>,
  'getBatchAvailability' : ActorMethod<[string], Array<BatchAvailability>>,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'getPackageById' : ActorMethod<[string], [] | [Package]>,
  'getTrek' : ActorMethod<[string], [] | [Trek]>,
  'getUserBookings' : ActorMethod<[string], Array<Booking>>,
  'getYatra' : ActorMethod<[string], [] | [Yatra]>,
  'listAllReviews' : ActorMethod<[], Array<Review>>,
  'listBatches' : ActorMethod<[string], Array<Batch>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listGearItems' : ActorMethod<[], Array<GearItem>>,
  'listPackages' : ActorMethod<[], Array<Package>>,
  'listReviews' : ActorMethod<[string], Array<Review>>,
  'listTreks' : ActorMethod<[], Array<Trek>>,
  'listUserBookings' : ActorMethod<[string], Array<Booking>>,
  'listYatras' : ActorMethod<[], Array<Yatra>>,
  'searchTreks' : ActorMethod<[string], Array<Trek>>,
  'submitBookingInquiry' : ActorMethod<[BookingInquiry], string>,
  'updateBatchAvailability' : ActorMethod<[string, bigint], boolean>,
  'updatePaymentStatus' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];