/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ParticipantInput {
    age: bigint;
    govtIdType: string;
    medicalConditions: string;
    email: string;
    gender: string;
    emergencyContactPhone: string;
    emergencyContactName: string;
    mobile: string;
    lastName: string;
    govtIdNumber: string;
    firstName: string;
}
export interface BlogPost {
    id: string;
    title: string;
    date: string;
    imageQuery: string;
    excerpt: string;
    category: string;
}
export interface BookingInput {
    participants: Array<ParticipantInput>;
    promoCode: string;
    advanceAmount: bigint;
    totalAmount: bigint;
    addOns: AddOns;
    trekSlug: string;
    paymentType: string;
    batchDate: string;
}
export interface Trek {
    id: string;
    region: string;
    duration: string;
    difficulty: string;
    name: string;
    bestTime: string;
    description: string;
    imageQuery: string;
    distance: string;
    nearestAirport: string;
    price: string;
    maxAltitude: string;
    nearestRailhead: string;
    groupSize: string;
    startPoint: string;
    ageGroup: string;
}
export interface BookingInquiry {
    trekInterest: string;
    name: string;
    email: string;
    hearAboutUs: string;
    preferredDates: string;
    phone: string;
    groupSize: string;
    specialRequirements: string;
}
export interface Package {
    id: string;
    duration: string;
    name: string;
    description: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    category: string;
    price: bigint;
    images: Array<string>;
}
export interface BatchAvailability {
    totalSeats: bigint;
    bookedSeats: bigint;
    availableSeats: bigint;
    trekSlug: string;
    price: bigint;
    batchDate: string;
    batchType: string;
}
export interface Batch {
    id: string;
    endDate: string;
    maxCapacity: bigint;
    trekId: string;
    bookedCount: bigint;
    basePrice: bigint;
    batchType: string;
    startDate: string;
}
export interface Yatra {
    id: string;
    region: string;
    duration: string;
    startEnd: string;
    difficulty: string;
    name: string;
    bestTime: string;
    description: string;
    imageQuery: string;
    price: string;
}
export interface AddOns {
    gearTent: boolean;
    gearBoots: boolean;
    porterDays: bigint;
    mule: boolean;
    muleDays: bigint;
    gearSleepingBag: boolean;
    travelInsurance: boolean;
    porter: boolean;
}
export interface Booking {
    id: string;
    status: BookingStatus;
    participants: Array<ParticipantInput>;
    userId: string;
    createdAt: bigint;
    promoCode: string;
    advanceAmount: bigint;
    totalAmount: bigint;
    addOns: AddOns;
    trekSlug: string;
    contactEmail: string;
    paymentType: string;
    paidAmount: bigint;
    batchDate: string;
    contactPhone: string;
}
export interface Review {
    id: string;
    verified: boolean;
    userId: string;
    trekId: string;
    reviewerCity: string;
    reviewText: string;
    reviewerName: string;
    trekDate: string;
    rating: bigint;
    helpful: bigint;
}
export interface GearItem {
    id: string;
    name: string;
    spec: string;
    deposit: bigint;
    pricePerDay: bigint;
    category: string;
    brand: string;
}
export enum BookingStatus {
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export interface backendInterface {
    cancelBooking(bookingId: string, _reason: string): Promise<boolean>;
    createBooking(input: BookingInput): Promise<string>;
    createReview(review: Review): Promise<string>;
    getAvailableSeats(trekSlug: string, batchDate: string): Promise<bigint>;
    getBatchAvailability(trekSlug: string): Promise<Array<BatchAvailability>>;
    getBooking(bookingId: string): Promise<Booking | null>;
    getPackageById(packageId: string): Promise<Package | null>;
    getTrek(id: string): Promise<Trek | null>;
    getUserBookings(contactEmail: string): Promise<Array<Booking>>;
    getYatra(yatraId: string): Promise<Yatra | null>;
    listAllReviews(): Promise<Array<Review>>;
    listBatches(trekId: string): Promise<Array<Batch>>;
    listBlogPosts(): Promise<Array<BlogPost>>;
    listGearItems(): Promise<Array<GearItem>>;
    listPackages(): Promise<Array<Package>>;
    listReviews(trekId: string): Promise<Array<Review>>;
    listTreks(): Promise<Array<Trek>>;
    listUserBookings(userId: string): Promise<Array<Booking>>;
    listYatras(): Promise<Array<Yatra>>;
    searchTreks(searchTerm: string): Promise<Array<Trek>>;
    submitBookingInquiry(inquiry: BookingInquiry): Promise<string>;
    updateBatchAvailability(batchId: string, seatsBooked: bigint): Promise<boolean>;
    updatePaymentStatus(bookingId: string, paidAmount: bigint): Promise<boolean>;
}
import type { AddOns as _AddOns, Booking as _Booking, BookingStatus as _BookingStatus, Package as _Package, ParticipantInput as _ParticipantInput, Trek as _Trek, Yatra as _Yatra } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelBooking(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createReview(arg0: Review): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0);
            return result;
        }
    }
    async getAvailableSeats(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSeats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSeats(arg0, arg1);
            return result;
        }
    }
    async getBatchAvailability(arg0: string): Promise<Array<BatchAvailability>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchAvailability(arg0);
            return result;
        }
    }
    async getBooking(arg0: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackageById(arg0: string): Promise<Package | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackageById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackageById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrek(arg0: string): Promise<Trek | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrek(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrek(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBookings(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYatra(arg0: string): Promise<Yatra | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getYatra(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYatra(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllReviews();
            return result;
        }
    }
    async listBatches(arg0: string): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBatches(arg0);
            return result;
        }
    }
    async listBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts();
            return result;
        }
    }
    async listGearItems(): Promise<Array<GearItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGearItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGearItems();
            return result;
        }
    }
    async listPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPackages();
            return result;
        }
    }
    async listReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviews(arg0);
            return result;
        }
    }
    async listTreks(): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTreks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTreks();
            return result;
        }
    }
    async listUserBookings(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserBookings(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserBookings(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listYatras(): Promise<Array<Yatra>> {
        if (this.processError) {
            try {
                const result = await this.actor.listYatras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listYatras();
            return result;
        }
    }
    async searchTreks(arg0: string): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTreks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTreks(arg0);
            return result;
        }
    }
    async submitBookingInquiry(arg0: BookingInquiry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingInquiry(arg0);
            return result;
        }
    }
    async updateBatchAvailability(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatchAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatchAvailability(arg0, arg1);
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Package]): Package | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trek]): Trek | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Yatra]): Yatra | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    participants: Array<_ParticipantInput>;
    userId: string;
    createdAt: bigint;
    promoCode: string;
    advanceAmount: bigint;
    totalAmount: bigint;
    addOns: _AddOns;
    trekSlug: string;
    contactEmail: string;
    paymentType: string;
    paidAmount: bigint;
    batchDate: string;
    contactPhone: string;
}): {
    id: string;
    status: BookingStatus;
    participants: Array<ParticipantInput>;
    userId: string;
    createdAt: bigint;
    promoCode: string;
    advanceAmount: bigint;
    totalAmount: bigint;
    addOns: AddOns;
    trekSlug: string;
    contactEmail: string;
    paymentType: string;
    paidAmount: bigint;
    batchDate: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n4(_uploadFile, _downloadFile, value.status),
        participants: value.participants,
        userId: value.userId,
        createdAt: value.createdAt,
        promoCode: value.promoCode,
        advanceAmount: value.advanceAmount,
        totalAmount: value.totalAmount,
        addOns: value.addOns,
        trekSlug: value.trekSlug,
        contactEmail: value.contactEmail,
        paymentType: value.paymentType,
        paidAmount: value.paidAmount,
        batchDate: value.batchDate,
        contactPhone: value.contactPhone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): BookingStatus {
    return "Confirmed" in value ? BookingStatus.Confirmed : "Cancelled" in value ? BookingStatus.Cancelled : "Completed" in value ? BookingStatus.Completed : "Pending" in value ? BookingStatus.Pending : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
